# -*- coding: utf-8 -*-
"""IPL 2026 analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1khVN8BAdkgte2iQgKluFI6E3EUfoRpbO
"""

# IMPORTING NUMPYS AND PANDAS

import numpy as np
import pandas as pd

# IMPORT DATASET

ipl = pd.read_csv('/content/ipl_2026_deliveries.csv')
# SHAPE OF DATASET
print(ipl.shape)
# TOP 5 ROWS OF DATASET
ipl.head(5)

#TOTAL RUNS IN IPL 2026

ipl['runs_of_bat'].sum()

"""### BATTING ANALYSIS"""

# most scored run in ipl by
ipl.groupby('striker')['runs_of_bat'].sum().sort_values(ascending=False).head(1)

#TOP 10 PLAYERS WITH HIGHEST RUNS

ipl.groupby('striker')['runs_of_bat'].sum().sort_values(ascending=False).head(10)

# MOST 4'S IN innings IPL 2026

four = ipl[ipl['runs_of_bat'] == 4]

result = (four.groupby(['striker', 'match_id', 'innings'])['runs_of_bat']
.size()
    .reset_index(name='fours')
    .sort_values('fours',ascending=False)
    .head(1)
)
print(result)

# MOST 6'S IN innings IPL 2026
six = ipl[ipl['runs_of_bat'] == 6]
res = (six.groupby(['striker', 'match_id', 'innings'])['runs_of_bat']
  .size()
  .reset_index(name ='sixes')
  .sort_values('sixes',ascending=False)
  .head(1)
)
print(res)

# MOST 6'S IN  IPL 2026
six = ipl[ipl['runs_of_bat'] == 6]
six.groupby('striker')['runs_of_bat'].count().sort_values(ascending=False).head(1)

# MOST 4'S IN  IPL 2026
four = ipl[ipl['runs_of_bat'] == 4]
four.groupby('striker')['runs_of_bat'].count().sort_values(ascending=False).head(1)

# BEST STRIKE RATE IN A INNING


ipl['balls_faced_delivery'] = ((ipl['wide'] == 0) & (ipl['noballs'] == 0)).astype(int)


innings_stats = ipl.groupby(['striker', 'match_id', 'innings']).agg(
    total_runs_bat_innings=('runs_of_bat', 'sum'),
    total_balls_faced_innings=('balls_faced_delivery', 'sum')
).reset_index()


# Strike Rate = (Total Runs Scored / Total Balls Faced) * 100

innings_stats['strike_rate'] = innings_stats.apply(
    lambda row: (row['total_runs_bat_innings'] / row['total_balls_faced_innings']) * 100
    if row['total_balls_faced_innings'] > 0 else 0,
    axis=1
)

# Filter for players who have faced a minimum of 5 balls
filtered_innings_stats = innings_stats[innings_stats['total_balls_faced_innings'] >= 5]

# Sort by strike rate in descending order and get the top one from the filtered data
best_strike_rate_inning = filtered_innings_stats.sort_values('strike_rate', ascending=False).head(1)

print(best_strike_rate_inning)

# BATTER SCORED HIGHEST  RUN IN SINGLE MATCH
ipl.groupby(['match_id','striker'])['runs_of_bat'].sum().sort_values(ascending=False).head(1)